language: rust
rust:
  - 1.41.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt
cache: cargo
script:
  - cargo build --verbose
  - cargo fmt -- --check
  - cargo test --verbose
