[package]
name = "stay_the_course"
version = "0.1.0"
authors = ["David Cain <davidjosephcain@gmail.com>"]

[dependencies]
quick-xml = "0.13.1"
rust_decimal = ">= 0.11.2"
rusqlite = "0.16.0"
chrono = "0.4.6"
csv = "1"
serde = "1"
serde_derive = "1"
num = "0.2.0"
