[package]
name = "stay_the_course"
version = "0.1.0"
authors = ["David Cain <davidjosephcain@gmail.com>"]

[dependencies]
quick-xml = "0.13.1"
rust_decimal = "0.11.*"
rusqlite = "0.16.0"
chrono = "0.4.6"
